spring:
  application:
    name: railway-reservation-I
  datasource:
    url: jdbc:mysql://localhost:3306/springbootlearning
    username: springbootuser
    password: password

train:
  start: A
  end: Z
  count:
    seats: 8
    wait: 2